service: mba-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    SECRET_NAME: credenciaisMba

  iamRoleStatements:
    # leitura do Secret Manager
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource:
        - arn:aws:secretsmanager:us-east-1:047719652186:secret:credenciaisMba-*

    # invocação das lambdas internas
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:047719652186:function:mba-backend-${self:provider.stage}-executarSql
        - arn:aws:lambda:us-east-1:047719652186:function:mba-backend-${self:provider.stage}-schemaInspector

functions:
  agent:
    handler: services/agent/index.handler
    events:
      - httpApi:
          path: /agent
          method: post

  executarSql:
    handler: services/executar-sql/index.handler

  schemaInspector:
    handler: services/schema-inspector/index.handler

plugins:
  - serverless-esbuild
