name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LARAVEL_API_URL: ${{ secrets.LARAVEL_API_URL }}
      LARAVEL_TOKEN: ${{ secrets.LARAVEL_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies for Backend
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy with Serverless
        run: npm run deploy

      - name: List Serverless output (debug)
        run: ls -R .serverless || echo "No .serverless folder found"

        

      